### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by calebschoepp**

### CODE REVIEW

**Comment by armiantos** [comment]
OMG loool 😂

**Comment by calebschoepp** [comment]
> OMG loool

Lol Cyrus and I were using this to test deployments on Heroku. Can you approve it though? :smile:

**Comment by armiantos** [comment]
Ah my bad I thought we also wanted to update the README contents explaining what the project is hahahha. Approved

**Review by armiantos — APPROVED** [review]
LGTM!

**Comment by calebschoepp** [comment]
> Ah my bad I thought we also wanted to update the README contents explaining what the project is hahahha. Approved

Lol I mean we do, but I'm just punting that to a future PR haha.

**Pull request merged**
