### PR TITLE
Rachel/profile drop

### PR DESCRIPTION
**Pull request by rachel-ellis**
# Overview

Drop down menu with a logout button

# Changes

- components/auth/AuthButton.tsx
- components/auth/UserProfile.tsx
- components/Header.tsx

# Questions & Notes

# Issue tracking

Addressing part of #112 

# Testing & Demo

### CODE REVIEW

**Review by cyrusdiego — CHANGES_REQUESTED** [review]
Nice work with this! Just left a comment and I'm also seeing an error in the dev tools 
image

**Comment by armiantos** [comment]
@cyrusdiego are you still seeing the error?

**Comment by cyrusdiego** [comment]
@armiantos lol getting a new error now 
image

**Comment by armiantos** [comment]
Yea sadly this is a [material UI limitation](https://github.com/mui-org/material-ui/issues/13394) as far as I know 🥲

**Review by armiantos — APPROVED** [review]
LGTM! We might want to do a clean up PR some time in the future

**Pull request merged**
